{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f968cf50-75f9-4fe1-8559-119ba02ae9fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "# app.py\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import classification_report, roc_auc_score\n",
    "import pickle\n",
    "\n",
    "st.set_page_config(page_title=\"Loan Approval App\", layout=\"centered\")\n",
    "st.title(\"🏦 Loan Approval Prediction Web App\")\n",
    "\n",
    "uploaded_file = st.sidebar.file_uploader(\"Upload your loan dataset (CSV)\", type=[\"csv\"])\n",
    "\n",
    "if uploaded_file:\n",
    "    df = pd.read_csv(uploaded_file)\n",
    "    st.subheader(\"📊 Dataset Preview\")\n",
    "    st.write(df.head())\n",
    "\n",
    "    required_cols = ['loan_amount', 'annual_income', 'credit_score', 'interest_rate', 'loan_status']\n",
    "    if not set(required_cols).issubset(df.columns):\n",
    "        st.error(f\"Dataset must include: {', '.join(required_cols)}\")\n",
    "    else:\n",
    "        df.fillna(df.median(numeric_only=True), inplace=True)\n",
    "\n",
    "        X = df[['loan_amount', 'annual_income', 'credit_score', 'interest_rate']]\n",
    "        y = df['loan_status']\n",
    "\n",
    "        scaler = StandardScaler()\n",
    "        X_scaled = scaler.fit_transform(X)\n",
    "\n",
    "        X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)\n",
    "\n",
    "        model_name = st.sidebar.selectbox(\"Choose a model\", [\"Gradient Boosting\", \"Logistic Regression\"])\n",
    "        model = GradientBoostingClassifier() if model_name == \"Gradient Boosting\" else LogisticRegression()\n",
    "\n",
    "        model.fit(X_train, y_train)\n",
    "        y_pred = model.predict(X_test)\n",
    "\n",
    "        with open(\"loan_model.pkl\", \"wb\") as f:\n",
    "            pickle.dump(model, f)\n",
    "\n",
    "        st.subheader(\"✅ Model Performance\")\n",
    "        st.text(\"Classification Report:\")\n",
    "        st.text(classification_report(y_test, y_pred))\n",
    "        st.text(\"AUC-ROC Score: {:.2f}\".format(roc_auc_score(y_test, y_pred)))\n",
    "\n",
    "        st.subheader(\"🎯 Predict Loan Approval\")\n",
    "        loan_amount = st.number_input(\"Loan Amount\", 500, 50000, 10000)\n",
    "        annual_income = st.number_input(\"Annual Income\", 10000, 200000, 60000)\n",
    "        credit_score = st.slider(\"Credit Score\", 300, 850, 700)\n",
    "        interest_rate = st.slider(\"Interest Rate (%)\", 1.0, 25.0, 10.0)\n",
    "\n",
    "        if st.button(\"Predict\"):\n",
    "            input_data = scaler.transform([[loan_amount, annual_income, credit_score, interest_rate]])\n",
    "            prediction = model.predict(input_data)\n",
    "            if prediction[0] == 1:\n",
    "                st.success(\"✅ Loan Approved\")\n",
    "            else:\n",
    "                st.error(\"❌ Loan Denied\")\n",
    "else:\n",
    "    st.info(\"Please upload a CSV file to continue.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
